from setuptools import setup, find_packages

setup(
    name='Department App',
    version='1.0',
    author='Oleksandr Chabdaev',
    author_email='o.chabdaev@gmail.com',
    description='Web application for managing departments and employees',
    url='https://github.com/OleksandrChabdaev/epam-python-onlineua-autumn-2021-final-project',
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        'alembic==1.7.5',
        'aniso8601==9.0.1',
        'astroid==2.9.0',
        'click==8.0.3',
        'colorama==0.4.4',
        'Flask==2.0.2',
        'Flask-Migrate==3.1.0',
        'Flask-RESTful==0.3.9',
        'Flask-SQLAlchemy==2.5.1',
        'Flask-WTF==1.0.0',
        'greenlet==1.1.2',
        'gunicorn==20.1.0',
        'isort==5.10.1',
        'itsdangerous==2.0.1',
        'Jinja2==3.0.3',
        'lazy-object-proxy==1.6.0',
        'Mako==1.1.6',
        'MarkupSafe==2.0.1',
        'mccabe==0.6.1',
        'mysql-connector-python==8.0.27',
        'platformdirs==2.4.0',
        'protobuf==3.19.1',
        'pylint==2.12.2',
        'python-decouple==3.5',
        'pytz==2021.3',
        'six==1.16.0',
        'SQLAlchemy==1.4.27',
        'toml==0.10.2',
        'Werkzeug==2.0.2',
        'wrapt==1.13.3',
        'WTForms==3.0.0'
    ]
)
